services:
  mock-bio-service:
    build:
      context: .
      dockerfile: Dockerfile

    container_name: mock-bio-service

    ports:
      - "8001:8000"

    volumes:
      - ./app:/app/app

    command: >
      uvicorn app.main:app
      --host 0.0.0.0
      --port 8000
      --reload

    networks:
      - bio-network

    restart: unless-stopped

networks:
  bio-network:
    external: true
